USE ROLE TRAFFIC_DLT_ROLE;

USE WAREHOUSE TRAFFIC_WH;
USE DATABASE TRAFFIC_ANALYTICS_DB;

USE SCHEMA TRAFFIC_ANALYTICS_DB.STAGING;

SHOW TABLES IN SCHEMA;

SELECT * FROM TRAFIKVERKET_DATA LIMIT 10;

SELECT COUNT(*) FROM TRAFIKVERKET_DATA;

SELECT 
    COUNT(*)
FROM 
    TRAFIKVERKET_DATA
WHERE 
    START_TIME > '2024-09-24';

SELECT
    START_TIME,
    END_TIME,
    HEADER,
    MESSAGE_CODE,
    AFFECTED_DIRECTION,
    LOCATION_DESCRIPTOR,
    TRAFFIC_RESTRICTION_TYPE,
FROM
    TRAFIKVERKET_DATA
WHERE
    START_TIME > '2024-09-24';


