USE ROLE SECURITYADMIN;

CREATE USER IF NOT EXISTS Rickard
  PASSWORD = 'hej123'
  MUST_CHANGE_PASSWORD = True
  DEFAULT_ROLE = 'TRAFFIC_DLT_ROLE'
  DEFAULT_WAREHOUSE = 'TRAFFIC_WH';

GRANT ROLE SYSADMIN TO USER Rickard;