USE ROLE SECURITYADMIN;

CREATE USER IF NOT EXISTS traffic_dlt_user
  PASSWORD = 'traffic_dlt_user'
  MUST_CHANGE_PASSWORD = FALSE
  DEFAULT_ROLE = 'TRAFFIC_DLT_ROLE'
  DEFAULT_WAREHOUSE = 'TRAFFIC_WH';