USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS traffic_dlt_role;

GRANT ROLE traffic_dlt_role TO USER traffic_dlt_user;

GRANT USAGE ON WAREHOUSE TRAFFIC_WH TO ROLE traffic_dlt_role;
GRANT USAGE ON DATABASE TRAFFIC_ANALYTICS_DB TO ROLE traffic_dlt_role;
GRANT USAGE ON SCHEMA TRAFFIC_ANALYTICS_DB.staging TO ROLE traffic_dlt_role;
GRANT CREATE TABLE ON SCHEMA TRAFFIC_ANALYTICS_DB.staging TO ROLE traffic_dlt_role;
GRANT 
    SELECT,
    INSERT,
    UPDATE,
    DELETE
    ON ALL TABLES IN SCHEMA TRAFFIC_ANALYTICS_DB.staging TO ROLE traffic_dlt_role;

GRANT
    SELECT,
    INSERT,
    UPDATE,
    DELETE
    ON FUTURE TABLES IN SCHEMA TRAFFIC_ANALYTICS_DB.staging TO ROLE traffic_dlt_role;

GRANT ROLE traffic_dlt_role TO USER QWIIRE;