USE ROLE SYSADMIN;
CREATE WAREHOUSE IF NOT EXISTS TRAFFIC_WH
  WITH WAREHOUSE_SIZE = 'XSMALL'
  WAREHOUSE_TYPE = 'STANDARD'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  MIN_CLUSTER_COUNT = 1
  MAX_CLUSTER_COUNT = 2
  SCALING_POLICY = 'STANDARD'
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Warehouse for Traffic Data';

CREATE DATABASE IF NOT EXISTS TRAFFIC_ANALYTICS_DB;

CREATE SCHEMA IF NOT EXISTS TRAFFIC_ANALYTICS_DB.staging;