api_secret_key = "api_secret_key" # please set me up!

[destination.snowflake.credentials]
database = "traffic_analytics_db" # please set me up!
password = "traffic_dlt_user" # please set me up!
username = "traffic_dlt_user" # please set me up!
host = "rx96840.west-europe.azure" # please set me up!
warehouse = "traffic_wh" # please set me up!
role = "traffic_dlt_role" # please set me up!